### ISSUE TITLE
Error "too many arguments"

### ISSUE THREAD

**Issue by DayVeeBoi** [korikori/ideapad-perf#3]
Hi, how's it going? I am wondering if you can help me out? I'm trying to use ideapad-perf on Legion 5 17ACH6H (Ryzen 7 5800h + Nvidia RTX3060). I know that conservation mode is functional, since I'm able to verify it using 'tlp-stats -b'. However, I am not sure if rapid charge enable/disable works.  

When I use the applet, I see several errors. Here is  the term output:
```
sudo ./ideapad-perf-tray.rb 
[sudo] password for dayvee: 
/usr/local/bin/ideapad-perf: line 42: [: too many arguments
/usr/local/bin/ideapad-perf: line 44: [: too many arguments
/usr/local/bin/ideapad-perf: line 46: [: too many arguments
/usr/local/bin/ideapad-perf: line 42: [: too many arguments
/usr/local/bin/ideapad-perf: line 44: [: too many arguments
/usr/local/bin/ideapad-perf: line 46: [: too many arguments
```
A similar error occurs when executing the script alone:
```
sudo ideapad-perf --check
/usr/local/bin/ideapad-perf: line 42: [: too many arguments
/usr/local/bin/ideapad-perf: line 44: [: too many arguments
/usr/local/bin/ideapad-perf: line 46: [: too many arguments
Rapid Charge mode is , Battery Conservation mode is .
```
When I tried using the script without sudo, the error message was different:
```
/usr/local/bin/ideapad-perf: line 42: [: ==: unary operator expected
/usr/local/bin/ideapad-perf: line 44: [: ==: unary operator expected
/usr/local/bin/ideapad-perf: line 46: [: ==: unary operator expected
```
Thanks for all your work on this project. If you need any other information, just let me know.

**Comment by korikori** [comment]
Hi there, and thanks for trying this out. This script seems to work on Legion laptops only partially - see https://github.com/korikori/ideapad-perf/issues/2 where the same error is reported at some point down the replies. More specifically, lines 42/44/46 have to do with making and then confirming an ACPI call to put the laptop in the three different performance states (outside of the two battery modes) - intelligent cooling, battery saving, and extreme performance. 

As I've replied to the other issue's reporter, if the ACPI calls for these performance modes on the Legion laptops are different, the script can be modified, but I don't know what these calls are. They have also reported success with a different way of modifying and checking their battery performance mode, which doesn't use ACPI calls and instead relies on the "ideapad" driver - the problem in that is you would have to use sudo to use the script, which is something I'm trying to avoid on principle. BTW your examples show that you're using sudo too - do you receive different errors without it? 

Some questions: Have you tried running https://github.com/0xless/battmngr? Do you have an idea for the ACPI calls to set the performance modes for your model? And are you interested in a limited script/applet that only deals with the two modes for the battery - rapid charging and battery conservation?

**Comment by DayVeeBoi** [comment]
Hi again, thanks for the response.
> Do you have an idea for the ACPI calls to set the performance modes for your model?
>
I do not know the ACPI calls, but the POP!_OS power settings tool is able to change it ([System76-power)](https://github.com/orgs/pop-os/repositories?q=power&type=all&language=&sort=). I am willing to try and figure out what they are if you want to add them. 
>are you interested in a limited script/applet that only deals with the two modes for the battery - rapid charging and battery conservation?
>
Yes, I'd be interested, the battery functions are what I'm most interested in. If you're too busy or just not interested, I understand and if I figure the calls out I will post them here, or submit a PR. I don't mind using the command line to change charging modes, since it's not often that I need to change them.

>Have you tried running https://github.com/0xless/battmngr?
>
I am using battmgr now. Performance mode setting is non-functional, but it does read the current perf mode correctly (I have one of the Fn+Q Lenovos). The battery mode can both be set and read  back correctly.
> BTW your examples show that you're using sudo too - do you receive different errors without it?
> 
Yes, I do get different errors without sudo:
```
$ ./ideapad-perf -vb
./ideapad-perf: line 41: /proc/acpi/call: Permission denied
cat: /proc/acpi/call: Permission denied
./ideapad-perf: line 43: /proc/acpi/call: Permission denied
cat: /proc/acpi/call: Permission denied
Rapid Charge mode is , Battery Conservation mode is .
$ ./ideapad-perf -b rapid
Setting battery mode to Rapid Charge (with Battery Conservation disabled)...
./ideapad-perf: line 58: /proc/acpi/call: Permission denied
./ideapad-perf: line 60: /proc/acpi/call: Permission denied
./ideapad-perf: line 41: /proc/acpi/call: Permission denied
cat: /proc/acpi/call: Permission denied
./ideapad-perf: line 43: /proc/acpi/call: Permission denied
cat: /proc/acpi/call: Permission denied
Rapid Charge mode is , Battery Conservation mode is .

```
I appreciate you taking the time to help.

**Comment by DayVeeBoi** [comment]
> I do not know the ACPI calls, but the POP!_OS power settings tool is able to change it

I am wrong about this, please ignore it.

**Comment by korikori** [comment]
Hi, sorry for the delay, I haven't completely forgotten about you :) Can you check if you have the following files and if so, what their contents are:
* `cat /sys/firmware/acpi/platform_profile`
* `cat /sys/firmware/acpi/platform_profile_choices`
* `cat /sys/firmware/acpi/pm_profile`

Can you also try running these pairs of commands in sequence - e.g. the first echo, then the first cat, etc:

* `echo '\_SB.PCI0.LPC0.EC0.FCGM' | tee /proc/acpi/call`
`cat /proc/acpi/call; printf '\n'`

* `echo '\_SB.PCI0.LPC0.EC0.QCHO' > /proc/acpi/call`
`cat /proc/acpi/call; printf '\n'`

* `echo '\_SB.PCI0.LPC0.EC0.QKCM' | tee /proc/acpi/call`
`cat /proc/acpi/call | cut -d '' -f1`

On these three pairs, we're looking for something like 0x0 or 0x1.

Thanks

**Comment by DayVeeBoi** [comment]
Hi, sorry for not responding sooner. I tried to check the commands when I first saw your reply, but I quickly ran into trouble, so I put it off until I had more time to (attempt to) sort it out.  From a [quick search](https://wccftech.com/acpi-platform-profile-support-for-lenovo-amd-based-systems-on-linux-broken/), it seems that platform profile support may be lacking on newer Lenovo devices.
IDK if this might have something to do with it, but I'm using PopOS on this machine. They have their own ACPI kernel module and I have errors relating to that in dmesg and journalctl (If it is not apparent, I don't know anything about this stuff lmao). 

cat /sys/firmware/acpi/platform_profile
`cat: /sys/firmware/acpi/platform_profile: No such file or directory`
cat /sys/firmware/acpi/platform_profile_choices
`cat: /sys/firmware/acpi/platform_profile_choices: No such file or directory`
cat /sys/firmware/acpi/pm_profile
`2`

\_SB.PCI0.LPC0.EC0.FCGM
`Error: AE_NOT_FOUND`
\_SB.PCI0.LPC0.EC0.QCHO
`0x0`
\_SB.PCI0.LPC0.EC0.QKCM
`Error: AE_NOT_FOUND`

**Comment by korikori** [comment]
Thanks for getting back and the commands' output. I've been re-reading your previous comments and I don't think I can improve upon this:
> I am using battmgr now. Performance mode setting is non-functional, but it does read the current perf mode correctly (I have one of the Fn+Q Lenovos). The battery mode can both be set and read back correctly.

The major difference between my script and battmgr is that the latter uses sudo, which I want to avoid; conversely, this is what allows for the applet (I wouldn't want it to run with administrator privileges). So the only thing you're missing out on is the applet. I would've done that for battmgr in the first place if it weren't for the sudo thing.

**Comment by korikori** [comment]
I am closing this issue for now as I don't expect to work on it further for the time being. Feel free to reopen it if you have new information that may be helpful.

**Comment by DayVeeBoi** [comment]
Hey, I forgot to say thanks. I meant to do so long ago, and it slipped my mind. I appreciate that you took the time to have a look at my issue.

**Comment by korikori** [comment]
You are welcome - I'm sorry that I couldn't be of more help!
