### ISSUE TITLE
Dependencies for the python applet(s)

### ISSUE THREAD

**Issue by ervinpopescu** [korikori/ideapad-perf#8]
I'd recommend that you add the following dependencies to the README:  `python, pygtk, python-gobject`. These are Arch `pkgnames`.

**Comment by ervinpopescu** [comment]
More or less the `python` one since that's most likely on the system anyways :)

**Comment by korikori** [comment]
Done, thanks!

**Comment by ervinpopescu** [comment]
Hey, I made a mistake and it turns out the only one that's needed is `python-gobject` as that is for GTK3 and later (`/usr/lib/python3.10/site-packages/gi/ is owned by python-gobject 3.42.2-1`) and `pygtk` is for GTK2...
