### ISSUE TITLE
[Bug] [Suggestion] make selected option stands out.

### ISSUE THREAD

**Issue by raisinbl** [korikori/ideapad-perf#9]
### Suggestion 
(for Python)
- the python version **must** be 3.10, I've try on 3.11 and it doesn't work because it will raise exception on `from gi.repository import AppIndicator3`
- may be a requirements.txt for python package like: PyGObject, pycairo; [here](https://pygobject.readthedocs.io/en/latest/getting_started.html#arch-logo-arch-linux]) that make everyone easier to follow if they using virtual environment
-  Can you kind of make the selected option stand out, like make a dot or tick or highlight,...

### my problem
I using Arch, python 3.10 and I've install all necessary package to run the `ideapad-perf-tray.py`, 
- without `sudo`, the tray applet will appear but its function will not work.
- with `sudo`, the tray applet will not appear, raise `Segmentation fault` at the end and here's the log
```sh
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified


(ideapad-perf-tray.py:10620): Gtk-CRITICAL **: 22:57:30.463: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
/home/hung/arch/utils/ideapad-perf/ideapad-perf-tray.py:20: Warning: invalid (NULL) pointer instance
  self.indicator = appindicator.Indicator.new(
/home/hung/arch/utils/ideapad-perf/ideapad-perf-tray.py:20: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.indicator = appindicator.Indicator.new(

(ideapad-perf-tray.py:10620): Gtk-CRITICAL **: 22:57:30.466: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(ideapad-perf-tray.py:10620): Gtk-CRITICAL **: 22:57:30.466: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(ideapad-perf-tray.py:10620): Gtk-CRITICAL **: 22:57:30.466: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault
```

**Comment by korikori** [comment]
Sorry for the delay in getting back to you. Regarding the following:
> without sudo, the tray applet will appear but its function will not work.

I assume that you are not using one of the packaged releases, as they don't contain the Python applet. Have you manually applied/installed the udev rules from https://github.com/korikori/ideapad-perf/blob/main/81-ideapadperf.rules? For a quick test, you can run the chgrp and chmod commands from that file manually, and see if that fixes anything.

Also: does the Ruby applet work? Does the CLI utility work?

**Comment by raisinbl** [comment]
Thank you for replying.

> Also: does the Ruby applet work? Does the CLI utility work?
- CLI script works really well.
- I'm not get used to Ruby so I've not tryin yet (probably I've tried to find and install necessary Ruby packages, it raise exception so I decided not to spend more time on Ruby 😅, but I thought I'm gonna try later, so sorry bout that)

> Have you manually applied/installed the udev rules from https://github.com/korikori/ideapad-perf/blob/main/81-ideapadperf.rules?

that's why I'm curios how da hell this file was in the repo, sorry again for not reading carefully.
> You can download the script, make it executable, and add it to your path. You can run it with sudo, or you can install the supplied udev rule to make /proc/acpi/call writeable to all members of the wheel group.

I've tried as you suggested and it works, tysm!. I provided my procedure step, for whom like me
 - copy `81-ideapadperf.rules` to `/etc/udev/rules.d`
 - reload rules: `# udevadm control --reload`
 - manual trigger rules: `# udevadm trigger`
 - `chgrp wheel ideapad-perf-tray.py`
 - logout, login and magic 
 
 Once again thank you so much for spending time writing valuable script, keep it up bro.
 
 p/s: I see your demo screenshot with highlight on selection,can you provide what your system tray or status bar package name you use. I use Hyprland as WM and waybar but the applet not highlight my selection or current selection.

**Comment by korikori** [comment]
Thanks for the feedback, glad that you managed to resolve it and it works for you! I am using `tint2` as the bottom panel/system tray. However, please note that the screenshot is from the original Ruby applet. The Python applet was contributed by someone else here on GitHub, so it may use different Gtk selectors - I haven't really tested it that much other than I know it can work :)
